name = "elina"
author = "fripp"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "386fbd984157a90fee75fa60318dd88bb36057de4d562145fa44daf5b20fadd7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
